apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-kernel-repo-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
