# Copyright 2026 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: syz-agent
namePrefix: prod-

resources:
  - ../../common
  - ../../common/lore-relay

images:
  - name: gcr.io/syzkaller/syz-agent
    newName: ${IMAGE_NAME}
    newTag: ${IMAGE_TAG}
  - name: gcr.io/syzkaller/lore-relay
    newName: ${LORE_RELAY_IMAGE_NAME}
    newTag: ${LORE_RELAY_IMAGE_TAG}

configMapGenerator:
  - name: syz-agent-config
    files:
      - config.json=agent-config.json
  - name: lore-relay-config
    files:
      - lore-relay-config.yaml=lore-relay-config.yaml

patches:
  - target:
      kind: StatefulSet
      name: syz-agent
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          amd64-nested-virtualization: "true"
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: "workload"
            operator: "Equal"
            value: "nested-vm"
            effect: "NoSchedule"
