apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: argo-workflow-role 
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["list", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-list-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default 
  namespace: default 
roleRef:
  kind: Role
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io
