apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blob-storage-disk-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
