// Copyright 2015/2016 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package main

import (
	"bytes"
	"cmp"
	"flag"
	"fmt"
	"go/format"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"sync"
	"text/template"

	"github.com/google/syzkaller/pkg/ast"
	"github.com/google/syzkaller/pkg/compiler"
	"github.com/google/syzkaller/pkg/hash"
	"github.com/google/syzkaller/pkg/osutil"
	"github.com/google/syzkaller/pkg/tool"
	"github.com/google/syzkaller/prog"
	"github.com/google/syzkaller/sys/generated"
	"github.com/google/syzkaller/sys/targets"
)

type SyscallData struct {
	Name     string
	CallName string
}

type Define struct {
	Name  string
	Value string
}

type ArchData struct {
	Revision   string
	ForkServer int
	GOARCH     string
	PageSize   uint64
	NumPages   uint64
	DataOffset uint64
	Calls      []SyscallData
	Defines    []Define
}

type OSData struct {
	GOOS  string
	Archs []ArchData
}

type CallPropDescription struct {
	Type string
	Name string
}

type TemplateData struct {
	Notice    string
	OSes      []OSData
	CallProps []CallPropDescription
}

var srcDir = flag.String("src", "", "path to root of syzkaller source dir")
var outDir = flag.String("out", "", "path to out dir")

func main() {
	defer tool.Init()()

	// Cleanup old files in the case set of architectures has changed.
	allFiles, err := filepath.Glob(filepath.Join(*outDir, "sys", generated.Glob()))
	if err != nil {
		tool.Failf("failed to glob: %v", err)
	}
	for _, file := range allFiles {
		os.Remove(file)
	}

	// Also remove old generated files since they will break build.
	// TODO: remove this after some time after 2025-01-23.
	oldFiles, err := filepath.Glob(filepath.Join(*outDir, "sys", "*", "gen", "*"))
	if err != nil {
		tool.Failf("failed to glob: %v", err)
	}
	for _, file := range oldFiles {
		os.Remove(file)
	}

	OSList := slices.Sorted(maps.Keys(targets.List))

	data := &TemplateData{
		Notice: "Automatically generated by syz-sysgen; DO NOT EDIT.",
	}
	for _, OS := range OSList {
		descriptions := ast.ParseGlob(filepath.Join(*srcDir, "sys", OS, "*.txt"), nil)
		if descriptions == nil {
			os.Exit(1)
		}
		constFile := compiler.DeserializeConstFile(filepath.Join(*srcDir, "sys", OS, "*.const"), nil)
		if constFile == nil {
			os.Exit(1)
		}

		archs := slices.Sorted(maps.Keys(targets.List[OS]))

		var jobs []*Job
		for _, arch := range archs {
			target := targets.List[OS][arch]
			constInfo := compiler.ExtractConsts(descriptions, target, nil)
			if OS == targets.TestOS {
				// The ConstFile object provides no guarantees re concurrent read-write,
				// so let's patch it before we start goroutines.
				compiler.FabricateSyscallConsts(target, constInfo, constFile)
			}
			jobs = append(jobs, &Job{
				Target:      target,
				Unsupported: make(map[string]bool),
				ConstInfo:   constInfo,
			})
		}
		slices.SortFunc(jobs, func(a, b *Job) int {
			return cmp.Compare(a.Target.Arch, b.Target.Arch)
		})
		var wg sync.WaitGroup
		wg.Add(len(jobs))

		for _, job := range jobs {
			go func() {
				defer wg.Done()
				processJob(job, descriptions, constFile)
			}()
		}
		wg.Wait()

		var syscallArchs []ArchData
		unsupported := make(map[string]int)
		for _, job := range jobs {
			if !job.OK {
				fmt.Printf("compilation of %v/%v target failed:\n", job.Target.OS, job.Target.Arch)
				for _, msg := range job.Errors {
					fmt.Print(msg)
				}
				os.Exit(1)
			}
			syscallArchs = append(syscallArchs, job.ArchData)
			for u := range job.Unsupported {
				unsupported[u]++
			}
		}
		data.OSes = append(data.OSes, OSData{
			GOOS:  OS,
			Archs: syscallArchs,
		})

		for what, count := range unsupported {
			if count == len(jobs) {
				tool.Failf("%v is unsupported on all arches (typo?)", what)
			}
		}
	}

	props := prog.CallProps{}
	props.ForeachProp(func(name, _ string, value reflect.Value) {
		data.CallProps = append(data.CallProps, CallPropDescription{
			Type: value.Kind().String(),
			Name: prog.CppName(name),
		})
	})

	slices.SortFunc(data.OSes, func(a, b OSData) int {
		return cmp.Compare(a.GOOS, b.GOOS)
	})

	writeTemplate(filepath.Join(*outDir, "sys", "register.go"), registerTempl, data)
	writeTemplate(filepath.Join(*outDir, "executor", "defs.h"), defsTempl, data)
	writeTemplate(filepath.Join(*outDir, "executor", "syscalls.h"), syscallsTempl, data)
}

type Job struct {
	Target      *targets.Target
	OK          bool
	Errors      []string
	Unsupported map[string]bool
	ArchData    ArchData
	ConstInfo   map[string]*compiler.ConstInfo
	Revision    string
}

func processJob(job *Job, descriptions *ast.Description, constFile *compiler.ConstFile) {
	eh := func(pos ast.Pos, msg string) {
		job.Errors = append(job.Errors, fmt.Sprintf("%v: %v\n", pos, msg))
	}
	consts := constFile.Arch(job.Target.Arch)
	prg := compiler.Compile(descriptions, consts, job.Target, eh)
	if prg == nil {
		return
	}
	for what := range prg.Unsupported {
		job.Unsupported[what] = true
	}

	data, err := generated.Serialize(prg.TargetDesc(consts))
	if err != nil {
		tool.Fail(err)
	}
	sysFile := filepath.Join(*outDir, "sys", generated.FileName(job.Target.OS, job.Target.Arch))
	writeFile(sysFile, data)

	job.ArchData = generateExecutorSyscalls(job.Target, prg.Syscalls, hash.String(data))

	// Don't print warnings, they are printed in syz-check.
	job.Errors = nil
	// But let's fail on always actionable errors.
	if job.Target.OS != targets.Fuchsia {
		// There are too many broken consts on Fuchsia.
		constsAreAllDefined(constFile, job.ConstInfo, eh)
	}
	job.OK = len(job.Errors) == 0
}

func generateExecutorSyscalls(target *targets.Target, syscalls []*prog.Syscall, rev string) ArchData {
	data := ArchData{
		Revision:   rev,
		GOARCH:     target.Arch,
		PageSize:   target.PageSize,
		NumPages:   target.NumPages,
		DataOffset: target.DataOffset,
	}
	if target.ExecutorUsesForkServer {
		data.ForkServer = 1
	}
	defines := make(map[string]string)
	seenCalls := make(map[string]bool)
	for _, c := range syscalls {
		if call, ok := newSyscallData(target, c); ok && !seenCalls[call.Name] {
			seenCalls[call.Name] = true
			data.Calls = append(data.Calls, call)
		}
		// Some syscalls might not be present on the compiling machine, so we
		// generate definitions for them.
		if target.HasCallNumber(c.CallName) && target.NeedSyscallDefine(c.NR) {
			defines[target.SyscallPrefix+c.CallName] = fmt.Sprintf("%d", c.NR)
		}
	}
	slices.SortFunc(data.Calls, func(a, b SyscallData) int {
		return cmp.Compare(a.Name, b.Name)
	})
	// Get a sorted list of definitions.
	defineNames := slices.Sorted(maps.Keys(defines))
	for _, key := range defineNames {
		data.Defines = append(data.Defines, Define{key, defines[key]})
	}
	return data
}

func newSyscallData(target *targets.Target, sc *prog.Syscall) (SyscallData, bool) {
	callName, patchCallName := target.SyscallTrampolines[sc.CallName]
	if !patchCallName {
		callName = sc.CallName
	}
	needCall := (!target.HasCallNumber(sc.CallName) || patchCallName) &&
		// These are declared in the compiler for internal purposes.
		!strings.HasPrefix(sc.CallName, "syz_builtin")
	if !needCall {
		return SyscallData{}, false
	}
	return SyscallData{
		Name:     sc.CallName,
		CallName: callName,
	}, true
}

func writeTemplate(file string, templ *template.Template, data any) {
	buf := new(bytes.Buffer)
	if err := templ.Execute(buf, data); err != nil {
		tool.Failf("failed to execute template: %v", err)
	}
	contents := buf.Bytes()
	if strings.HasSuffix(file, ".go") {
		var err error
		contents, err = format.Source(contents)
		if err != nil {
			tool.Failf("failed to format generated source: %v", err)
		}
	}
	writeFile(file, contents)
}

func writeFile(file string, data []byte) {
	if current, err := os.ReadFile(file); err == nil && bytes.Equal(data, current) {
		return
	}
	osutil.MkdirAll(filepath.Dir(file))
	if err := osutil.WriteFile(file, data); err != nil {
		tool.Failf("failed to write output file: %v", err)
	}
}

// nolint: lll
var registerTempl = template.Must(template.New("register").Parse(`// {{.Notice}}

package sys

import (
	"embed"

	"github.com/google/syzkaller/sys/generated"
	{{range $os := $.OSes}}
	"github.com/google/syzkaller/sys/{{$os.GOOS}}"{{end}}
)

//go:embed gen/*.gob.flate
var files embed.FS

func init() {
	{{range $os := $.OSes}}{{range $arch := $os.Archs}}generated.Register("{{$os.GOOS}}", "{{$arch.GOARCH}}", "{{$arch.Revision}}", {{$os.GOOS}}.InitTarget, files)
	{{end}}{{end}}
}
`))

var defsTempl = template.Must(template.New("defs").Parse(`// {{.Notice}}

struct call_props_t { {{range $attr := $.CallProps}}
	{{$attr.Type}} {{$attr.Name}};{{end}}
};

#define read_call_props_t(var, reader) { \{{range $attr := $.CallProps}}
	(var).{{$attr.Name}} = ({{$attr.Type}})(reader); \{{end}}
}

{{range $os := $.OSes}}
#if GOOS_{{$os.GOOS}}
#define GOOS "{{$os.GOOS}}"
{{range $arch := $os.Archs}}
#if GOARCH_{{$arch.GOARCH}}
#define GOARCH "{{.GOARCH}}"
#define SYZ_REVISION "{{.Revision}}"
#define SYZ_EXECUTOR_USES_FORK_SERVER {{.ForkServer}}
#define SYZ_PAGE_SIZE {{.PageSize}}
#define SYZ_NUM_PAGES {{.NumPages}}
#define SYZ_DATA_OFFSET {{.DataOffset}}
{{range $c := $arch.Defines}}#ifndef {{$c.Name}}
#define {{$c.Name}} {{$c.Value}}
#endif
{{end}}#endif
{{end}}
#endif
{{end}}
`))

var syscallsTempl = template.Must(template.New("syscalls").Parse(`// {{.Notice}}
// clang-format off
{{range $os := $.OSes}}
#if GOOS_{{$os.GOOS}}
{{range $arch := $os.Archs}}
#if GOARCH_{{$arch.GOARCH}}
const pseudo_syscall_t pseudo_syscalls[] = {
{{range $c := $arch.Calls}}    {"{{$c.Name}}", (syscall_t){{$c.CallName}}},
{{end}}    {nullptr, nullptr},
};
#endif
{{end}}
#endif
{{end}}
`))
