FROM golang:1.23-alpine AS builder

WORKDIR /build

# Prepare the dependencies.
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Build the tool.
COPY pkg/ pkg/
COPY db-mgmt/*.go db-mgmt/
RUN go build -o /bin/db-mgmt /build/db-mgmt

# Create the actual container.
FROM alpine:latest
WORKDIR /app

COPY --from=builder /bin/db-mgmt /bin/db-mgmt
COPY ./db-mgmt/migrations/*.sql /migrations/

CMD ["/bin/db-mgmt" "migrate" "/migrations"]
