# Copyright 2026 syzkaller project authors. All rights reserved.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: exp-${EXP_NAME}-

resources:
  - job.yaml
  - ../../common/agent/network
  - ../prod-agent/config

images:
  - name: gcr.io/syzkaller/syz-agent
    newName: ${IMAGE_NAME}
    newTag: ${IMAGE_TAG}

components:
  - ../../common/agent/workload-patches

# We must manually map the generated ConfigMap name into the Job because 
# Kustomize's name reference mapping natively targets StatefulSets but not Jobs.
replacements:
  - source:
      kind: ConfigMap
      name: syz-agent-config
      fieldPath: metadata.name
    targets:
      - select:
          kind: Job
          name: syz-agent
        fieldPaths:
          - spec.template.spec.volumes.[name=config-volume].configMap.name
